apiVersion: apps/v1
kind: Deployment
metadata:
  name: q1dockerapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: q1dockerapp
  template:
    metadata:
      labels:
        app: q1dockerapp
    spec:
      containers:
        - name: q1dockerapp
          image: shobitha22/q1dockerapp:latest
          ports:
            - containerPort: 80
